language: perl
perl:
  - 5.12
  - 5.14
  - 5.16
  - 5.18

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -delete 

script:
  - perl Build.PL 
  - ./Build build 
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/

after_success:
  - cover -report coveralls

